---
# Persistent volume for model storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-models
  labels:
    app: inference
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
