---
# Exposes the Ollama inference server

apiVersion: v1
kind: Service
metadata:
  name: token-loom
  labels:
    app: token-loom
spec:
  type: {{ .Values.service.type }}
  selector:
    app: token-loom
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
